language: c
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libcairo2-dev libpango1.0-dev libtokyocabinet-dev imagemagick
script: 
  - autoreconf -i 
  - ./configure
  - make
  - sudo make install
  - sudo duc index -x /
  - sudo duc ls /usr
  - sudo duc draw /
  - identify duc.png
