name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Install required dependencies
      run: sudo apt-get install libncursesw5-dev libcairo2-dev libpango1.0-dev build-essential libtokyocabinet-dev
    - name: aclocal
      run: aclocal
    - name: autoreconf
      run: autoreconf -i
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
